#!/usr/bin/env bash
# PreToolUse guard on Write|Edit for the synthpass-docpoet subagent. A docpoet repairs
# references, indices and drift in prose; it does not change code, measurements, the corpus,
# or CI-owned numbers.
#
# Allowed targets:
#   knowledge/**.md                    the knowledge tree, including ADR prose
#   README.md CONTRIBUTING.md SECURITY.md CHANGELOG.md THIRD_PARTY*.md
#   the session scratchpad             (…/Temp/claude/…)
# Denied even inside the allowed tree:
#   knowledge/benchmarks/real-specimen-mrz-baseline.json — written only by CI
#   samples/**                         the corpus and its manifest are generated, not edited
#   crates/** .github/** scripts/** tools/**
#
# Matching is on a repo-relative SUFFIX, deliberately, and not on `cwd`-stripping. A linked
# worktree session reports `cwd` as the MAIN checkout while the target file lives under
# D:/Projects/worktrees/..., so a cwd-relative rule denies every allowlisted path in a worktree
# and pushes the agent towards writing the file some other way. That happened: an agent hit the
# false denial and fell back to `cp` via Bash, which this hook does not see. A guard that is
# wrong in a common case does not get obeyed, it gets routed around — so the deny rules below
# are suffix-matched too, and are evaluated FIRST, which is what keeps the guard honest
# wherever the session happens to be rooted.

in=$(cat)
path=$(printf '%s' "$in" | grep -oE '"file_path":[[:space:]]*"([^"\\]|\\.)*"' | head -1 \
  | sed -E 's/^"file_path":[[:space:]]*"//; s/"$//; s/\\\\/\//g; s#\\/#/#g')

deny() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"synthpass-docpoet writes only Markdown under knowledge/ and the root doc set: %s. A code, corpus, manifest, script or baseline change goes in the report as a recommendation for the calling session, never as an edit."}}' "$1"
  exit 0
}

[ -n "$path" ] || deny "could not read file_path from the tool input"

# 1. Scratchpad is always fine, whatever it is rooted at.
case "$path" in
  */Temp/claude/*|*/temp/claude/*) exit 0 ;;
esac

# 2. Deny rules first, by suffix, so they hold in any checkout or worktree.
case "$path" in
  *real-specimen-mrz-baseline.json)
    deny "the baseline is produced only by CI (gh workflow run real-specimen-gate.yml -f mode=write-baseline)" ;;
  samples/*|*/samples/*)
    deny "samples/ is generated by corpus_manifest.rs and curated by the screener + maintainer; report manifest defects instead of editing them" ;;
  crates/*|*/crates/*|.github/*|*/.github/*|scripts/*|*/scripts/*|tools/*|*/tools/*)
    deny "$path is code or tooling, not prose" ;;
esac

# 3. Allow rules, also by suffix.
case "$path" in
  knowledge/*.md|*/knowledge/*.md) exit 0 ;;
  README.md|*/README.md) exit 0 ;;
  CONTRIBUTING.md|*/CONTRIBUTING.md) exit 0 ;;
  SECURITY.md|*/SECURITY.md) exit 0 ;;
  CHANGELOG.md|*/CHANGELOG.md) exit 0 ;;
  THIRD_PARTY*.md|*/THIRD_PARTY*.md) exit 0 ;;
  *) deny "$path is outside the docpoet's write scope" ;;
esac
