//! #477: an offline, deterministic audit of `translit.rs`'s `TABLE_A` against
//! the ISO 10646 character-name list.
//!
//! ICAO Doc 9303 Part 3 section 6, Table A ("Transliteration of Multinational
//! Latin-based Characters") assigns each of its 95 rows the ISO 10646 name of
//! the code point it prints. The ISO 10646 name list itself is held
//! privately; the Unicode Character Database's `UnicodeData.txt` carries the
//! same names publicly, so `TABLE_A_ISO10646_NAMES` below is checked against
//! it, never against ISO 10646 directly.
//!
//! `TABLE_A_ISO10646_NAMES` was produced independently of `translit.rs`'s own
//! row comments: for each of `TABLE_A`'s 95 code points, its official Unicode
//! name was looked up with Python's standard-library `unicodedata` module
//! (`unicodedata.unidata_version` reported `14.0.0` when this file was
//! written) and copied in below. `table_a_matches_its_iso10646_names` then
//! checks that this independently-derived (code point, name) list names
//! *exactly* the code points `TABLE_A` actually holds -- neither more nor
//! fewer -- which is the mechanical form of "every row is the character it
//! claims to be": a row whose code point had been swapped for a
//! similar-looking one would make this list disagree with `TABLE_A`'s live
//! contents. `every_row_transliterates_to_the_letter_its_name_implies` ties
//! each name to its row's output: every transliteration must begin with the
//! base letter the name reads (`B` for `LATIN CAPITAL LETTER B WITH ...`), so
//! the names are checked against the table, not just carried beside it.
//!
//! This crate stays zero-dependency, so no Unicode name database ships with
//! it or with this test -- the lookup above was performed once, offline, and
//! its result is inlined as plain string literals; `mrz::transliterations`
//! is the only crate API this file calls.
//!
//! The companion gap table for every `LATIN (CAPITAL|SMALL) LETTER ... WITH
//! ...` character `TABLE_A` does *not* cover lives at
//! `knowledge/docs9303/TABLE_A_LATIN_WITH_COVERAGE.md`, generated by
//! `tools/latin_letter_with_coverage.py`. `gap_characters_pass_through_unchanged`
//! below confirms, for a sample of that table's gaps, the behaviour it
//! documents in prose: `mrz::transliterate` never drops a character outside
//! `TABLE_A` -- it passes it through unchanged (upper-cased).

/// Every `TABLE_A` code point paired with its official Unicode name, sorted
/// ascending by code point (matching `TABLE_A`'s own order). See the module
/// doc comment for how this list was derived and why that derivation is
/// independent of `translit.rs`'s row comments.
const TABLE_A_ISO10646_NAMES: &[(char, &str)] = &[
    ('\u{00C0}', "LATIN CAPITAL LETTER A WITH GRAVE"),
    ('\u{00C1}', "LATIN CAPITAL LETTER A WITH ACUTE"),
    ('\u{00C2}', "LATIN CAPITAL LETTER A WITH CIRCUMFLEX"),
    ('\u{00C3}', "LATIN CAPITAL LETTER A WITH TILDE"),
    ('\u{00C4}', "LATIN CAPITAL LETTER A WITH DIAERESIS"),
    ('\u{00C5}', "LATIN CAPITAL LETTER A WITH RING ABOVE"),
    ('\u{00C6}', "LATIN CAPITAL LETTER AE"),
    ('\u{00C7}', "LATIN CAPITAL LETTER C WITH CEDILLA"),
    ('\u{00C8}', "LATIN CAPITAL LETTER E WITH GRAVE"),
    ('\u{00C9}', "LATIN CAPITAL LETTER E WITH ACUTE"),
    ('\u{00CA}', "LATIN CAPITAL LETTER E WITH CIRCUMFLEX"),
    ('\u{00CB}', "LATIN CAPITAL LETTER E WITH DIAERESIS"),
    ('\u{00CC}', "LATIN CAPITAL LETTER I WITH GRAVE"),
    ('\u{00CD}', "LATIN CAPITAL LETTER I WITH ACUTE"),
    ('\u{00CE}', "LATIN CAPITAL LETTER I WITH CIRCUMFLEX"),
    ('\u{00CF}', "LATIN CAPITAL LETTER I WITH DIAERESIS"),
    ('\u{00D0}', "LATIN CAPITAL LETTER ETH"),
    ('\u{00D1}', "LATIN CAPITAL LETTER N WITH TILDE"),
    ('\u{00D2}', "LATIN CAPITAL LETTER O WITH GRAVE"),
    ('\u{00D3}', "LATIN CAPITAL LETTER O WITH ACUTE"),
    ('\u{00D4}', "LATIN CAPITAL LETTER O WITH CIRCUMFLEX"),
    ('\u{00D5}', "LATIN CAPITAL LETTER O WITH TILDE"),
    ('\u{00D6}', "LATIN CAPITAL LETTER O WITH DIAERESIS"),
    ('\u{00D8}', "LATIN CAPITAL LETTER O WITH STROKE"),
    ('\u{00D9}', "LATIN CAPITAL LETTER U WITH GRAVE"),
    ('\u{00DA}', "LATIN CAPITAL LETTER U WITH ACUTE"),
    ('\u{00DB}', "LATIN CAPITAL LETTER U WITH CIRCUMFLEX"),
    ('\u{00DC}', "LATIN CAPITAL LETTER U WITH DIAERESIS"),
    ('\u{00DD}', "LATIN CAPITAL LETTER Y WITH ACUTE"),
    ('\u{00DE}', "LATIN CAPITAL LETTER THORN"),
    ('\u{0100}', "LATIN CAPITAL LETTER A WITH MACRON"),
    ('\u{0102}', "LATIN CAPITAL LETTER A WITH BREVE"),
    ('\u{0104}', "LATIN CAPITAL LETTER A WITH OGONEK"),
    ('\u{0106}', "LATIN CAPITAL LETTER C WITH ACUTE"),
    ('\u{0108}', "LATIN CAPITAL LETTER C WITH CIRCUMFLEX"),
    ('\u{010A}', "LATIN CAPITAL LETTER C WITH DOT ABOVE"),
    ('\u{010C}', "LATIN CAPITAL LETTER C WITH CARON"),
    ('\u{010E}', "LATIN CAPITAL LETTER D WITH CARON"),
    ('\u{0110}', "LATIN CAPITAL LETTER D WITH STROKE"),
    ('\u{0112}', "LATIN CAPITAL LETTER E WITH MACRON"),
    ('\u{0114}', "LATIN CAPITAL LETTER E WITH BREVE"),
    ('\u{0116}', "LATIN CAPITAL LETTER E WITH DOT ABOVE"),
    ('\u{0118}', "LATIN CAPITAL LETTER E WITH OGONEK"),
    ('\u{011A}', "LATIN CAPITAL LETTER E WITH CARON"),
    ('\u{011C}', "LATIN CAPITAL LETTER G WITH CIRCUMFLEX"),
    ('\u{011E}', "LATIN CAPITAL LETTER G WITH BREVE"),
    ('\u{0120}', "LATIN CAPITAL LETTER G WITH DOT ABOVE"),
    ('\u{0122}', "LATIN CAPITAL LETTER G WITH CEDILLA"),
    ('\u{0124}', "LATIN CAPITAL LETTER H WITH CIRCUMFLEX"),
    ('\u{0126}', "LATIN CAPITAL LETTER H WITH STROKE"),
    ('\u{0128}', "LATIN CAPITAL LETTER I WITH TILDE"),
    ('\u{012A}', "LATIN CAPITAL LETTER I WITH MACRON"),
    ('\u{012C}', "LATIN CAPITAL LETTER I WITH BREVE"),
    ('\u{012E}', "LATIN CAPITAL LETTER I WITH OGONEK"),
    ('\u{0130}', "LATIN CAPITAL LETTER I WITH DOT ABOVE"),
    ('\u{0131}', "LATIN SMALL LETTER DOTLESS I"),
    ('\u{0132}', "LATIN CAPITAL LIGATURE IJ"),
    ('\u{0134}', "LATIN CAPITAL LETTER J WITH CIRCUMFLEX"),
    ('\u{0136}', "LATIN CAPITAL LETTER K WITH CEDILLA"),
    ('\u{0139}', "LATIN CAPITAL LETTER L WITH ACUTE"),
    ('\u{013B}', "LATIN CAPITAL LETTER L WITH CEDILLA"),
    ('\u{013D}', "LATIN CAPITAL LETTER L WITH CARON"),
    ('\u{013F}', "LATIN CAPITAL LETTER L WITH MIDDLE DOT"),
    ('\u{0141}', "LATIN CAPITAL LETTER L WITH STROKE"),
    ('\u{0143}', "LATIN CAPITAL LETTER N WITH ACUTE"),
    ('\u{0145}', "LATIN CAPITAL LETTER N WITH CEDILLA"),
    ('\u{0147}', "LATIN CAPITAL LETTER N WITH CARON"),
    ('\u{014A}', "LATIN CAPITAL LETTER ENG"),
    ('\u{014C}', "LATIN CAPITAL LETTER O WITH MACRON"),
    ('\u{014E}', "LATIN CAPITAL LETTER O WITH BREVE"),
    ('\u{0150}', "LATIN CAPITAL LETTER O WITH DOUBLE ACUTE"),
    ('\u{0152}', "LATIN CAPITAL LIGATURE OE"),
    ('\u{0154}', "LATIN CAPITAL LETTER R WITH ACUTE"),
    ('\u{0156}', "LATIN CAPITAL LETTER R WITH CEDILLA"),
    ('\u{0158}', "LATIN CAPITAL LETTER R WITH CARON"),
    ('\u{015A}', "LATIN CAPITAL LETTER S WITH ACUTE"),
    ('\u{015C}', "LATIN CAPITAL LETTER S WITH CIRCUMFLEX"),
    ('\u{015E}', "LATIN CAPITAL LETTER S WITH CEDILLA"),
    ('\u{0160}', "LATIN CAPITAL LETTER S WITH CARON"),
    ('\u{0162}', "LATIN CAPITAL LETTER T WITH CEDILLA"),
    ('\u{0164}', "LATIN CAPITAL LETTER T WITH CARON"),
    ('\u{0166}', "LATIN CAPITAL LETTER T WITH STROKE"),
    ('\u{0168}', "LATIN CAPITAL LETTER U WITH TILDE"),
    ('\u{016A}', "LATIN CAPITAL LETTER U WITH MACRON"),
    ('\u{016C}', "LATIN CAPITAL LETTER U WITH BREVE"),
    ('\u{016E}', "LATIN CAPITAL LETTER U WITH RING ABOVE"),
    ('\u{0170}', "LATIN CAPITAL LETTER U WITH DOUBLE ACUTE"),
    ('\u{0172}', "LATIN CAPITAL LETTER U WITH OGONEK"),
    ('\u{0174}', "LATIN CAPITAL LETTER W WITH CIRCUMFLEX"),
    ('\u{0176}', "LATIN CAPITAL LETTER Y WITH CIRCUMFLEX"),
    ('\u{0178}', "LATIN CAPITAL LETTER Y WITH DIAERESIS"),
    ('\u{0179}', "LATIN CAPITAL LETTER Z WITH ACUTE"),
    ('\u{017B}', "LATIN CAPITAL LETTER Z WITH DOT ABOVE"),
    ('\u{017D}', "LATIN CAPITAL LETTER Z WITH CARON"),
    ('\u{1E9E}', "LATIN CAPITAL LETTER SHARP S"),
];

#[test]
fn table_a_iso10646_names_has_95_entries() {
    assert_eq!(TABLE_A_ISO10646_NAMES.len(), 95);
}

#[test]
fn table_a_matches_its_iso10646_names() {
    // `mrz::transliterations` is the only public window onto `TABLE_A`'s
    // keys: non-empty exactly where a code point is one of its 95 rows.
    // Scanning past U+1E9E (TABLE_A's highest key, LATIN CAPITAL LETTER
    // SHARP S) with headroom finds every row without ever reading
    // `translit.rs` itself.
    let live_table_a: Vec<char> = ('\u{0000}'..='\u{2000}')
        .filter(|&c| !mrz::transliterations(c).is_empty())
        .collect();

    let mut named: Vec<char> = TABLE_A_ISO10646_NAMES.iter().map(|&(cp, _)| cp).collect();
    named.sort_unstable();
    named.dedup();
    assert_eq!(
        named.len(),
        TABLE_A_ISO10646_NAMES.len(),
        "TABLE_A_ISO10646_NAMES has a duplicate code point"
    );

    assert_eq!(
        live_table_a, named,
        "TABLE_A's live code points differ from the independently-named list: \
         a row's code point was likely swapped for a similar-looking one"
    );
}

/// Table A's five rows whose official name carries no `A`-`Z` base letter to
/// read off. Doc 9303 Part 3 section 6, Table A gives each one's
/// transliteration outright.
const NO_BASE_LETTER: &[(&str, &str)] = &[
    ("LATIN CAPITAL LETTER ETH", "D"),
    ("LATIN CAPITAL LETTER THORN", "TH"),
    ("LATIN SMALL LETTER DOTLESS I", "I"),
    ("LATIN CAPITAL LETTER ENG", "N"),
    ("LATIN CAPITAL LETTER SHARP S", "SS"),
];

/// The letters every transliteration of a row must begin with, read off its
/// official name alone: `B` for `LATIN CAPITAL LETTER B WITH ...`, `AE` for
/// `LATIN CAPITAL LETTER AE`, `IJ` for `LATIN CAPITAL LIGATURE IJ`, or the
/// fixed value in `NO_BASE_LETTER`. `None` for a name none of these covers.
fn implied_prefix(name: &str) -> Option<&str> {
    if let Some(&(_, fixed)) = NO_BASE_LETTER.iter().find(|&&(n, _)| n == name) {
        return Some(fixed);
    }
    let rest = name
        .strip_prefix("LATIN CAPITAL LETTER ")
        .or_else(|| name.strip_prefix("LATIN CAPITAL LIGATURE "))?;
    let base = rest.split(" WITH ").next()?;
    let is_letters = !base.is_empty() && base.chars().all(|c| c.is_ascii_uppercase());
    is_letters.then_some(base)
}

#[test]
fn every_row_transliterates_to_the_letter_its_name_implies() {
    for &(cp, name) in TABLE_A_ISO10646_NAMES {
        let prefix = implied_prefix(name)
            .unwrap_or_else(|| panic!("U+{:04X} {name}: no base letter to read off", cp as u32));
        let variants = mrz::transliterations(cp);
        assert!(
            !variants.is_empty(),
            "U+{:04X} {name} is not a Table A row",
            cp as u32
        );
        for variant in variants {
            assert!(
                variant.starts_with(prefix),
                "U+{:04X} {name}: transliteration {variant:?} does not begin with {prefix:?}",
                cp as u32
            );
        }
    }
}

#[test]
fn gap_characters_pass_through_unchanged() {
    // A sample of `knowledge/docs9303/TABLE_A_LATIN_WITH_COVERAGE.md`'s
    // "Gaps" section -- `LATIN ... WITH ...` characters with no `TABLE_A`
    // row, whose upper-case form is *also* not a `TABLE_A` row (so the
    // case-folding `transliterate` does before lookup can't find a hit
    // either). Doc 9303 recommends no transliteration for any of these;
    // `transliterate` must not drop them.
    let cases: &[(&str, &str)] = &[
        // U+01FA LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE: already
        // upper-case, and not a TABLE_A row -- passes through as itself.
        ("\u{01FA}", "\u{01FA}"),
        // U+01FB LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE upper-cases
        // to U+01FA, which is the gap above, not a TABLE_A row.
        ("\u{01FB}", "\u{01FA}"),
        // U+1E00 LATIN CAPITAL LETTER A WITH RING BELOW: already
        // upper-case, not a TABLE_A row.
        ("\u{1E00}", "\u{1E00}"),
        // U+1E03 LATIN SMALL LETTER B WITH DOT ABOVE upper-cases to U+1E02
        // (LATIN CAPITAL LETTER B WITH DOT ABOVE), not a TABLE_A row.
        ("\u{1E03}", "\u{1E02}"),
        // U+0180 LATIN SMALL LETTER B WITH STROKE upper-cases to U+0243
        // (LATIN CAPITAL LETTER B WITH STROKE), not a TABLE_A row.
        ("\u{0180}", "\u{0243}"),
    ];
    for (input, expected) in cases {
        for style in [
            mrz::TransliterationStyle::Expanded,
            mrz::TransliterationStyle::Simple,
            mrz::TransliterationStyle::XxSuffix,
        ] {
            assert_eq!(
                mrz::transliterate(input, style),
                *expected,
                "input {input:?} under {style:?}"
            );
        }
    }
}
