//! Property tests for the layout validator.
//!
//! - The validator never panics, whatever `u32` rectangles it is given.
//! - For layouts it accepts (generated by perturbing a built-in so acceptance is
//!   common): the watermark and MRZ are the frame's, the watermark band holds
//!   only the exact watermark colour and background and is seed-independent
//!   (PR 0's check), every label box lies inside the canvas, and every
//!   visual-zone value's ink lies inside its box.
//!
//! Cost: validation plus the ink and label sweep over seeds `0..INK_SEEDS` is
//! cheap (text measuring and label building, no rasterizing); the pixel checks
//! render `RENDER_SEEDS` seeds per accepted layout. `CASES` accepted-or-rejected
//! layouts per property. The numbers are in the PR body.

use proptest::prelude::*;
use proptest::test_runner::{Config, TestRunner};

use super::validated::tests::FORMATS;
use super::{frame_for, LayoutSpec, Rect, ValidatedLayout};
use crate::model::{DocumentType, GeneratorConfig};

const CASES: u32 = 64;
#[cfg(feature = "embedded-fonts")]
const INK_SEEDS: u64 = 200;
const RENDER_SEEDS: [u64; 3] = [0, 1, 42];

const BACKGROUND: [u8; 3] = [244, 243, 236];
const WATERMARK_COLOR: [u8; 3] = [176, 48, 48];

fn any_format() -> impl Strategy<Value = DocumentType> {
    prop::sample::select(FORMATS.to_vec())
}

fn any_rect() -> impl Strategy<Value = Rect> {
    (any::<u32>(), any::<u32>(), any::<u32>(), any::<u32>())
        .prop_map(|(x, y, width, height)| Rect::new(x, y, width, height))
}

fn spec_from(format: DocumentType, rects: &[Rect]) -> LayoutSpec {
    LayoutSpec {
        format,
        portrait: rects[0],
        document_type: rects[1],
        issuing_country: rects[2],
        surname: rects[3],
        given_names: rects[4],
        document_number: rects[5],
        nationality: rects[6],
        date_of_birth: rects[7],
        sex: rects[8],
        date_of_expiry: rects[9],
        personal_number: rects[10],
    }
}

/// A built-in with every rectangle nudged by a few pixels: small enough that
/// most results validate, large enough to hit every rule now and then.
fn perturbed_spec() -> impl Strategy<Value = LayoutSpec> {
    let delta = (-2i64..=2, -2i64..=2, -6i64..=12, -2i64..=2);
    (any_format(), prop::collection::vec(delta, 11)).prop_map(|(format, deltas)| {
        let base = LayoutSpec::builtin(format).rects();
        // The permitted area ends at the lowest built-in bottom, so a nudge
        // down would leave it for every rectangle that sits on that edge:
        // keep each nudged rectangle inside, so acceptance stays common.
        let bottom = frame_for(format).permitted.bottom().unwrap_or(u32::MAX);
        let moved: Vec<Rect> = base
            .iter()
            .zip(&deltas)
            .map(|(r, &(dx, dy, dw, dh))| {
                let add = |v: u32, d: i64| u32::try_from((i64::from(v) + d).max(1)).unwrap_or(1);
                let height = add(r.height, dh);
                Rect::new(
                    add(r.x, dx),
                    add(r.y, dy).min(bottom.saturating_sub(height)).max(1),
                    add(r.width, dw),
                    height,
                )
            })
            .collect();
        spec_from(format, &moved)
    })
}

proptest! {
    #![proptest_config(Config { cases: 512, ..Config::default() })]

    #[test]
    fn validation_never_panics_on_arbitrary_rectangles(
        format in any_format(),
        rects in prop::collection::vec(any_rect(), 11),
    ) {
        let _ = ValidatedLayout::try_from_spec(spec_from(format, &rects));
    }

    #[test]
    fn validation_never_panics_near_the_u32_limits(
        format in any_format(),
        rects in prop::collection::vec(
            (0u32..64, 0u32..64, 0u32..64, 0u32..64)
                .prop_map(|(a, b, c, d)| Rect::new(u32::MAX - a, u32::MAX - b, c, d)),
            11,
        ),
    ) {
        prop_assert!(ValidatedLayout::try_from_spec(spec_from(format, &rects)).is_err());
    }
}

#[cfg(feature = "embedded-fonts")]
fn check_ink_inside_boxes(layout: &ValidatedLayout) -> Result<(), TestCaseError> {
    use super::LayoutField;
    use crate::data::generate_passport;
    use crate::fonts::load_fonts;
    use crate::labels::build_labels_with_layout;
    use crate::render::{text_ink, viz_px_scale};

    let fonts = load_fonts().expect("embedded fonts load");
    let format = layout.format();
    for seed in 0..INK_SEEDS {
        let cfg = GeneratorConfig::with_document_type(seed, format);
        let passport = generate_passport(&cfg);
        let labels = build_labels_with_layout(&passport, layout);
        // What the visual zone draws: the native name where there is one.
        let surname = labels.surname_native.as_ref().unwrap_or(&labels.surname);
        let given = labels
            .given_names_native
            .as_ref()
            .unwrap_or(&labels.given_names);
        let mut drawn = vec![
            (LayoutField::DocumentType, &labels.document_type),
            (LayoutField::IssuingCountry, &labels.issuing_country),
            (LayoutField::Surname, surname),
            (LayoutField::GivenNames, given),
            (LayoutField::DocumentNumber, &labels.document_number),
            (LayoutField::Nationality, &labels.nationality),
            (LayoutField::DateOfBirth, &labels.date_of_birth),
            (LayoutField::Sex, &labels.sex),
            (LayoutField::DateOfExpiry, &labels.date_of_expiry),
        ];
        if let Some(pn) = &labels.personal_number {
            drawn.push((LayoutField::PersonalNumber, pn));
        }
        for (field, label) in drawn {
            let ink = text_ink(
                &fonts.viz,
                &label.value,
                label.rect,
                viz_px_scale(label.rect),
            );
            if let Some(ink) = ink {
                prop_assert!(
                    ink.within(label.rect),
                    "{format:?} seed {seed} {field}: {:?} inks {ink:?} outside {:?}",
                    label.value,
                    label.rect
                );
            }
        }
    }
    Ok(())
}

/// PR 0's exact watermark check, for one layout: the band holds only the
/// watermark colour and the background, at least one watermark pixel, and the
/// same mask for every seed.
fn check_rendered_pixels(layout: &ValidatedLayout) -> Result<(), TestCaseError> {
    let format = layout.format();
    let band = layout.page().watermark;
    let mut reference: Option<Vec<bool>> = None;
    for seed in RENDER_SEEDS {
        let cfg = GeneratorConfig::with_document_type(seed, format);
        let (image, labels, _) =
            crate::generate_from_seed_with_layout(&cfg, layout).map_err(TestCaseError::fail)?;
        let rgb = image.to_rgb8();
        prop_assert_eq!(
            (rgb.width(), rgb.height()),
            (layout.page().width, layout.page().height)
        );
        let mut mask = Vec::new();
        for y in band.y..band.y + band.height {
            for x in band.x..band.x + band.width {
                let px = rgb.get_pixel(x, y).0;
                prop_assert!(
                    px == WATERMARK_COLOR || px == BACKGROUND,
                    "{format:?} seed {seed}: ({x}, {y}) = {px:?} is neither watermark nor background"
                );
                mask.push(px == WATERMARK_COLOR);
            }
        }
        prop_assert!(
            mask.iter().any(|&on| on),
            "{format:?} seed {seed}: no watermark pixel"
        );
        match &reference {
            None => reference = Some(mask),
            Some(first) => prop_assert!(*first == mask, "{format:?}: mask differs at seed {seed}"),
        }
        // Every label box lies inside the canvas, the MRZ band included.
        let (w, h) = (layout.page().width, layout.page().height);
        let mut boxes = vec![
            labels.document_type.rect,
            labels.issuing_country.rect,
            labels.surname.rect,
            labels.given_names.rect,
            labels.document_number.rect,
            labels.nationality.rect,
            labels.date_of_birth.rect,
            labels.sex.rect,
            labels.date_of_expiry.rect,
            labels.mrz_rect,
        ];
        boxes.extend(labels.personal_number.as_ref().map(|l| l.rect));
        for rect in boxes {
            prop_assert!(
                rect.within_bounds(w, h),
                "{format:?}: {rect:?} outside {w}x{h}"
            );
        }
    }
    Ok(())
}

fn check_accepted(layout: &ValidatedLayout) -> Result<(), TestCaseError> {
    let format = layout.format();
    let frame = frame_for(format);
    prop_assert_eq!(layout.page().watermark, frame.watermark);
    prop_assert_eq!(&layout.page().mrz_lines, &frame.mrz_lines);
    prop_assert_eq!(layout.page().mrz_chars, frame.mrz_chars);
    prop_assert_eq!(
        (layout.page().width, layout.page().height),
        (frame.width, frame.height)
    );
    #[cfg(feature = "embedded-fonts")]
    check_ink_inside_boxes(layout)?;
    check_rendered_pixels(layout)
}

#[test]
fn accepted_layouts_keep_the_frame_the_watermark_and_the_ink_inside_their_boxes() {
    let mut runner = TestRunner::new(Config {
        cases: CASES,
        ..Config::default()
    });
    let accepted = std::cell::Cell::new(0u32);
    runner
        .run(&perturbed_spec(), |spec| {
            if let Ok(layout) = ValidatedLayout::try_from_spec(spec) {
                accepted.set(accepted.get() + 1);
                check_accepted(&layout)?;
            }
            Ok(())
        })
        .unwrap_or_else(|e| panic!("{e}"));
    let accepted = accepted.get();
    // Acceptance must be common, or the property proves nothing.
    #[cfg(feature = "embedded-fonts")]
    assert!(
        accepted * 4 >= CASES,
        "only {accepted} of {CASES} perturbed layouts validated"
    );
    eprintln!("accepted {accepted} of {CASES} perturbed layouts");
}
