//! Turn generated documents + packed rows into files on disk: JSONL, the
//! per-document PNGs, the manifest, and (for `--format hf`) the extra files the
//! `datasets` library reads. No network — ADR-0007 decision 3.

use std::fmt::Write as _;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::record::{GeneratedDoc, Row};
use crate::{ExportConfig, ExportError, ExportFormat, ExportSummary};

/// The `manifest.json` written at the dataset root — generated, never
/// hand-edited (`knowledge/EXPORTS.md`, "Manifest").
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Manifest {
    /// `synthpass-export` crate version.
    pub synthpass_version: String,
    /// `synthpass-gen` version — the labels' provenance. Same workspace
    /// version as `synthpass_version`.
    pub generator_version: String,
    pub format: String,
    pub created_unix: u64,
    pub seed_base: u64,
    pub count: u64,
    pub document_type: String,
    /// Always `"clean"` in v1 (`EXPORTS.md`, "Capture profiles").
    pub profile: String,
    pub pack_pages: u32,
    /// The exact `synthpass export …` command line that reproduces this export.
    pub command: String,
    pub files: Vec<ManifestFile>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ManifestFile {
    /// Path relative to the dataset root.
    pub path: String,
    pub sha256: String,
    pub rows: usize,
}

const WORKSPACE_VERSION: &str = env!("CARGO_PKG_VERSION");

pub(crate) fn write_dataset(
    cfg: &ExportConfig,
    docs: &[GeneratedDoc],
    rows: &[Row],
) -> Result<ExportSummary, ExportError> {
    let root = cfg.out_dir.as_path();
    std::fs::create_dir_all(root)?;

    // JSONL + images live at the root for `jsonl`, and under `data/` for `hf`
    // (so `datasets.load_dataset("<root>")` finds the split).
    let data_dir = match cfg.format {
        ExportFormat::Jsonl => root.to_path_buf(),
        ExportFormat::Hf => root.join("data"),
    };
    let images_dir = data_dir.join("images");
    std::fs::create_dir_all(&images_dir)?;

    // 1. Per-document PNGs. The record's `image` field is the path relative to
    //    the JSONL file, which sits in `data_dir`.
    for doc in docs {
        let path = data_dir.join(&doc.record.image);
        doc.image
            .save(&path)
            .map_err(|e| ExportError::Io(std::io::Error::other(e.to_string())))?;
    }

    // 2. JSONL — one compact object per line, trailing newline.
    let jsonl_name = match cfg.format {
        ExportFormat::Jsonl => "data.jsonl",
        ExportFormat::Hf => "train.jsonl",
    };
    let mut jsonl = Vec::new();
    for row in rows {
        serde_json::to_writer(&mut jsonl, row)?;
        jsonl.push(b'\n');
    }
    let jsonl_path = data_dir.join(jsonl_name);
    std::fs::write(&jsonl_path, &jsonl)?;

    let jsonl_rel = rel(root, &jsonl_path);
    let jsonl_sha = sha256_hex(&jsonl);

    // 3. Manifest.
    let manifest = Manifest {
        synthpass_version: WORKSPACE_VERSION.to_string(),
        generator_version: WORKSPACE_VERSION.to_string(),
        format: cfg.format.as_str().to_string(),
        created_unix: SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0),
        seed_base: cfg.seed_base,
        count: cfg.count,
        document_type: cfg.document_type.as_str().to_string(),
        profile: "clean".to_string(),
        pack_pages: cfg.pack_pages,
        command: cfg.command_line(),
        files: vec![ManifestFile {
            path: jsonl_rel,
            sha256: jsonl_sha,
            rows: rows.len(),
        }],
    };
    std::fs::write(
        root.join("manifest.json"),
        serde_json::to_string_pretty(&manifest)?,
    )?;

    // 4. Hugging Face extras.
    if cfg.format == ExportFormat::Hf {
        write_hf_extras(root, cfg, docs.len(), rows.len())?;
    }

    Ok(ExportSummary {
        rows: rows.len(),
        documents: cfg.count,
        out_dir: root.to_path_buf(),
        manifest,
    })
}

/// `dataset_infos.json` + `README.md` (the dataset card) — the two files that
/// make `datasets.load_dataset("<root>")` work offline and tell a reader what
/// they are holding.
fn write_hf_extras(
    root: &Path,
    cfg: &ExportConfig,
    num_docs: usize,
    num_rows: usize,
) -> Result<(), ExportError> {
    let infos = serde_json::json!({
        "default": {
            "description": "Synthetic ICAO 9303 identity-document corpus generated by SynthPass \
                            (synthpass-gen). Labels are 100% accurate by construction. Coordinates \
                            are normalised 0-1000 per knowledge/decisions/ADR-0007.",
            "citation": "",
            "homepage": "https://github.com/ruledicaprio/SynthPass",
            "license": "MIT",
            "splits": {
                "train": { "name": "train", "num_examples": num_rows }
            }
        }
    });
    std::fs::write(
        root.join("dataset_infos.json"),
        serde_json::to_string_pretty(&infos)?,
    )?;

    let mut card = String::new();
    let _ = write!(
        card,
        "---\n\
         license: mit\n\
         task_categories:\n\
         - image-to-text\n\
         tags:\n\
         - synthetic\n\
         - ocr\n\
         - mrz\n\
         - icao-9303\n\
         size_categories:\n\
         - {size}\n\
         ---\n\n\
         # SynthPass synthetic identity-document corpus\n\n\
         Generated by [SynthPass](https://github.com/ruledicaprio/SynthPass) \
         `synthpass export` — {docs} documents, {rows} rows, document type `{dtype}`, \
         seeds `{base}..{end}`, capture profile `clean`.\n\n\
         **Every document is unmistakably synthetic**: a mandatory \"SYNTHETIC / SPECIMEN\" \
         watermark and a generic, non-country template are rendered unconditionally, enforced \
         in code. These are testing and evaluation artefacts, never imitations of genuine \
         credentials.\n\n\
         Ground truth is 100% accurate by construction (not OCR-pseudo-labelled). Field boxes \
         are `[x0, y0, x1, y1]` normalised to 0-1000 of the image; the `ground_truth` string \
         follows the DeepSeek-OCR / Unlimited-OCR convention. Format and conventions: \
         `knowledge/decisions/ADR-0007-dataset-export-format.md` and `knowledge/EXPORTS.md` \
         in the SynthPass repository.\n\n\
         Load locally:\n\n\
         ```python\n\
         from datasets import load_dataset\n\
         ds = load_dataset(\"json\", data_files=\"data/train.jsonl\")\n\
         ```\n\n\
         Reproduce: `{cmd}`\n",
        size = size_bucket(num_rows),
        docs = num_docs,
        rows = num_rows,
        dtype = cfg.document_type.as_str(),
        base = cfg.seed_base,
        end = cfg.seed_base + cfg.count.saturating_sub(1),
        cmd = cfg.command_line(),
    );
    std::fs::write(root.join("README.md"), card)?;
    Ok(())
}

fn size_bucket(n: usize) -> &'static str {
    match n {
        0..=1_000 => "n<1K",
        1_001..=10_000 => "1K<n<10K",
        10_001..=100_000 => "10K<n<100K",
        100_001..=1_000_000 => "100K<n<1M",
        _ => "n>1M",
    }
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    // sha2 0.11's `finalize()` returns a `hybrid_array::Array` with no
    // `LowerHex`; format byte-by-byte, the same way `synthpass-ocr`'s
    // `build.rs` and corpus-manifest example do.
    let mut out = String::new();
    for b in hasher.finalize() {
        let _ = write!(out, "{b:02x}");
    }
    out
}

fn rel(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}
