#!/usr/bin/env python3
"""
index_findings.py

Regenerates the generated index block in `knowledge/benchmarks/FINDINGS.md`
between the `<!-- findings-index:start -->` / `<!-- findings-index:end -->`
markers -- one row per dated finding, newest first, drawn from three sources:

1. Every dated report file `knowledge/benchmarks/*-YYYY-MM-DD.md` (the 20
   files carrying the `**Date:** ... **MAIN:** ... **DATA:** ...
   **Evidence:** ... **Status:** ...` header standard).
2. Every `### YYYY-MM-DD -- Title` entry in `FINDINGS.md`'s own
   `## Weak-spot findings` section.
3. Every `## YYYY-MM-DD ...` section in `knowledge/WEB_OCR_BASELINE.md`.

Standard library only, matching every other `tools/` script.

## Usage

    python tools/index_findings.py --write   # regenerate the index in place
    python tools/index_findings.py --check   # exit 1 if the index is stale

`tools/rebless.py` calls `write_index()` directly after it appends a new
`## Weak-spot findings` entry, so the index is never one commit behind the
log it summarizes. CI runs `--check` on every PR (`.github/workflows/ci.yml`).

## The GitHub anchor rule, reverse-engineered

GitHub's heading-to-anchor algorithm is not documented as a stable contract,
so `github_anchor()` below was derived from this repository's own
self-referencing links inside `knowledge/benchmarks/README.md` (now moved to
`FINDINGS.md`) -- e.g. the heading "### 2026-08-16 -- first genuine
real-specimen Tier-1 numbers" is already linked elsewhere in that file as
`#2026-08-16--first-genuine-real-specimen-tier-1-numbers`. Three real
headings from that file are asserted against in
`tools/test_index_findings.py`. The rule: lowercase, drop every character
that is not a letter, digit, underscore, space or hyphen -- this removes an
em-dash *without* collapsing the whitespace it leaves behind -- then turn
each remaining space into a hyphen. An em-dash flanked by spaces (" -- ", one
character) therefore leaves TWO adjacent spaces once it is dropped, which
become a DOUBLE hyphen: "2026-08-16 -- first" -> "2026-08-16  first" ->
"2026-08-16--first". This is exactly why the double hyphens in this file's
own anchors are correct and not a formatting mistake.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

FINDINGS_REL_PATH = "knowledge/benchmarks/FINDINGS.md"
BENCH_DIR_REL_PATH = "knowledge/benchmarks"
WEB_OCR_REL_PATH = "knowledge/WEB_OCR_BASELINE.md"

INDEX_START = "<!-- findings-index:start -->"
INDEX_END = "<!-- findings-index:end -->"
GENERATED_COMMENT = "<!-- generated by `python tools/index_findings.py --write` -- do not edit by hand -->"

# `<stem>-YYYY-MM-DD.md`, matching every dated report file in
# knowledge/benchmarks/ -- FINDINGS.md, README.md, PIPELINE.md and the
# non-Markdown corpus/manifest files there never match (no trailing date).
REPORT_FILENAME_RE = re.compile(r"^.+-(?P<date>\d{4}-\d{2}-\d{2})\.md$")

# The header standard's one line, additive under each report file's title:
#   **Date:** YYYY-MM-DD · **MAIN:** <sha|not stated> · **DATA:** <sha|not stated> ·
#   **Evidence:** <label> · **Status:** <current | superseded by [...](...)>
HEADER_LINE_RE = re.compile(
    r"^\*\*Date:\*\*\s*(?P<date>\d{4}-\d{2}-\d{2})\s*·\s*"
    r"\*\*MAIN:\*\*\s*(?P<main>.+?)\s*·\s*"
    r"\*\*DATA:\*\*\s*(?P<data>.+?)\s*·\s*"
    r"\*\*Evidence:\*\*\s*(?P<evidence>.+?)\s*·\s*"
    r"\*\*Status:\*\*\s*(?P<status>.+)$"
)

# A bold evidence marker in an entry's first paragraph, e.g. "**Observed**" or
# "**Observed:**" or "**Observed.**" -- up to 3 trailing punctuation chars
# before the closing "**" are tolerated, matching how these are actually
# written in the log (see tools/test_index_findings.py).
EVIDENCE_MARKER_RE = re.compile(r"\*\*(Observed|Derived|Hypothesized)[^*]{0,3}\*\*")

# The three trailing date-suffix shapes a dated report file's `# ` title may
# carry, tried in the order given; only one can match a given title, since
# they are mutually exclusive end-of-string shapes.
TITLE_DATE_SUFFIX_PATTERNS = [
    re.compile(r"\s*—\s*\d{4}-\d{2}-\d{2}$"),  # "... -- 2026-08-05" (em-dash)
    re.compile(r"\s*\(\d{4}-\d{2}-\d{2}\)$"),  # "... (2026-09-12)"
    re.compile(r",\s*\d{4}-\d{2}-\d{2}$"),  # "..., 2026-09-05"
]

LOG_HEADING_RE = re.compile(r"^### (?P<date>\d{4}-\d{2}-\d{2}) — (?P<title>.+)$")
WEB_OCR_HEADING_RE = re.compile(r"^## (?P<date>\d{4}-\d{2}-\d{2})(?P<rest>.*)$")


@dataclass
class Entry:
    date: str
    title: str
    link: str
    evidence: str
    status: str
    where: str
    # Sort keys only -- never rendered. `file_label` disambiguates entries
    # that share a date ("filename asc"); `encounter_index` disambiguates
    # entries that share both a date and a file_label (several sections in
    # one source file dated the same day -- see the module docstring).
    file_label: str
    encounter_index: int


# ==========================================================================
# Pure helpers
# ==========================================================================


def strip_title_date_suffix(title: str) -> str:
    """Strips a trailing ", YYYY-MM-DD" / "(YYYY-MM-DD)" / "-- YYYY-MM-DD"
    date suffix from a dated report file's `# ` title, if present. A comma,
    parenthesis or em-dash earlier in the title (mid-sentence, not at the
    very end) is untouched -- only an end-of-string match strips anything."""
    for pattern in TITLE_DATE_SUFFIX_PATTERNS:
        stripped = pattern.sub("", title)
        if stripped != title:
            return stripped.rstrip()
    return title


def github_anchor(heading_text: str) -> str:
    """GitHub's heading-to-anchor rule -- see the module docstring for how
    this was derived and why a double hyphen after a removed em-dash is
    correct, not a bug."""
    lowered = heading_text.lower()
    kept = re.sub(r"[^a-z0-9_ -]", "", lowered)
    return kept.replace(" ", "-")


def md_table_cell(text: str) -> str:
    """Escapes the one character that would otherwise break a Markdown table
    row if a title ever contained it. None of today's titles do; this is
    defensive, not observed to matter yet."""
    return text.replace("|", "\\|")


def first_paragraph_evidence(body_lines: list[str]) -> str:
    """The Evidence value for a log entry or WEB_OCR_BASELINE.md section per
    the index rule: `—` unless the entry's first paragraph (the text up to
    the first blank line, or to the end of the body) carries a bold
    **Observed**/**Derived**/**Hypothesized** marker, in which case that
    word. The first matching marker wins when a paragraph carries more than
    one (e.g. the 2026-09-16 "provider-bench and synthpass-bench agree"
    entry states both **Observed:** and **Derived:**)."""
    idx = 0
    while idx < len(body_lines) and body_lines[idx].strip() == "":
        idx += 1
    paragraph: list[str] = []
    while idx < len(body_lines) and body_lines[idx].strip() != "":
        paragraph.append(body_lines[idx])
        idx += 1
    match = EVIDENCE_MARKER_RE.search(" ".join(paragraph))
    return match.group(1) if match else "—"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def first_heading(text: str, source: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    raise ValueError(f"{source}: no '# ' heading found")


def parse_report_header(text: str, source: str) -> dict:
    """Parses the header standard's one line out of a dated report file's
    text (anywhere in the file, though it is always the line directly under
    the title). Raises `ValueError` naming the file when the line is
    missing or malformed, rather than silently treating the report as
    unlabelled -- a missing header is a defect in the file, not a valid
    'nothing to report' state."""
    for line in text.splitlines():
        match = HEADER_LINE_RE.match(line.strip())
        if match:
            return match.groupdict()
    raise ValueError(f"{source}: no '**Date:** ... **Status:** ...' header line found")


# ==========================================================================
# Collecting entries from the three sources
# ==========================================================================


def collect_report_entries(root: Path) -> list[Entry]:
    bench_dir = root / BENCH_DIR_REL_PATH
    entries: list[Entry] = []
    for path in sorted(bench_dir.glob("*.md")):
        match = REPORT_FILENAME_RE.match(path.name)
        if not match:
            continue
        filename_date = match.group("date")
        text = read_text(path)
        title = strip_title_date_suffix(first_heading(text, path.name))
        header = parse_report_header(text, path.name)
        if header["date"] != filename_date:
            raise ValueError(
                f"{path.name}: header date {header['date']!r} does not match the filename's date {filename_date!r}"
            )
        entries.append(
            Entry(
                date=header["date"],
                title=title,
                link=path.name,
                evidence=header["evidence"],
                status=header["status"],
                where=path.name,
                file_label=path.name.lower(),
                encounter_index=0,
            )
        )
    return entries


def collect_findings_log_entries(root: Path) -> list[Entry]:
    findings_path = root / FINDINGS_REL_PATH
    text = read_text(findings_path)
    lines = text.splitlines()
    try:
        section_start = next(i for i, line in enumerate(lines) if line.strip() == "## Weak-spot findings")
    except StopIteration:
        raise ValueError(f"{FINDINGS_REL_PATH}: no '## Weak-spot findings' section found")

    entries: list[Entry] = []
    encounter_index = 0
    i = section_start + 1
    while i < len(lines):
        match = LOG_HEADING_RE.match(lines[i])
        if match is None:
            i += 1
            continue
        title_text = f"{match.group('date')} — {match.group('title')}"
        body_start = i + 1
        j = body_start
        while j < len(lines) and not lines[j].startswith("### "):
            j += 1
        entries.append(
            Entry(
                date=match.group("date"),
                # The heading embeds its date; the Date column already states it,
                # so the row shows the title alone while the anchor keeps the full
                # heading GitHub actually renders.
                title=match.group("title"),
                link=f"#{github_anchor(title_text)}",
                evidence=first_paragraph_evidence(lines[body_start:j]),
                status="current",
                where="FINDINGS.md (Weak-spot findings)",
                file_label="findings.md",
                encounter_index=encounter_index,
            )
        )
        encounter_index += 1
        i = j
    return entries


def collect_web_ocr_entries(root: Path) -> list[Entry]:
    web_ocr_path = root / WEB_OCR_REL_PATH
    text = read_text(web_ocr_path)
    lines = text.splitlines()

    entries: list[Entry] = []
    encounter_index = 0
    i = 0
    while i < len(lines):
        match = WEB_OCR_HEADING_RE.match(lines[i])
        if match is None:
            i += 1
            continue
        title_text = (match.group("date") + match.group("rest")).strip()
        body_start = i + 1
        j = body_start
        while j < len(lines) and not lines[j].startswith("## "):
            j += 1
        entries.append(
            Entry(
                date=match.group("date"),
                title=title_text,
                link=f"../WEB_OCR_BASELINE.md#{github_anchor(title_text)}",
                evidence=first_paragraph_evidence(lines[body_start:j]),
                status="current",
                where="WEB_OCR_BASELINE.md",
                file_label="web_ocr_baseline.md",
                encounter_index=encounter_index,
            )
        )
        encounter_index += 1
        i = j
    return entries


# ==========================================================================
# Ordering and rendering
# ==========================================================================


def sort_entries(entries: list[Entry]) -> list[Entry]:
    """Deterministic order: date descending (newest first), then
    `file_label` ascending, then `encounter_index` ascending -- the second
    sort is stable, so it preserves the first sort's tie order rather than
    needing a single composite key. `file_label` alone disambiguates same-
    date entries from different source files (several dated report files
    sharing one date); `encounter_index` only matters when both `date` and
    `file_label` are equal, i.e. several sections of *one* source file
    (FINDINGS.md's own log, or WEB_OCR_BASELINE.md) share a date -- in which
    case each source's own top-to-bottom order is preserved, since that is
    the only ordering either source states."""
    by_position = sorted(entries, key=lambda e: (e.file_label, e.encounter_index))
    return sorted(by_position, key=lambda e: e.date, reverse=True)


def render_row(entry: Entry) -> str:
    finding_cell = f"[{md_table_cell(entry.title)}]({entry.link})"
    return f"| {entry.date} | {finding_cell} | {entry.evidence} | {entry.status} | {entry.where} |"


def build_index_block(entries: list[Entry]) -> str:
    lines = [
        INDEX_START,
        GENERATED_COMMENT,
        "| Date | Finding | Evidence | Status | Where |",
        "| --- | --- | --- | --- | --- |",
    ]
    lines.extend(render_row(entry) for entry in entries)
    lines.append(INDEX_END)
    return "\n".join(lines)


def collect_all_entries(root: Path) -> list[Entry]:
    entries = collect_report_entries(root) + collect_findings_log_entries(root) + collect_web_ocr_entries(root)
    return sort_entries(entries)


def replace_index_block(findings_text: str, new_block: str) -> str:
    start = findings_text.find(INDEX_START)
    end = findings_text.find(INDEX_END)
    if start == -1 or end == -1:
        raise ValueError(f"{FINDINGS_REL_PATH}: missing {INDEX_START!r} / {INDEX_END!r} markers")
    end += len(INDEX_END)
    return findings_text[:start] + new_block + findings_text[end:]


def regenerated_findings_text(root: Path) -> tuple[str, str]:
    """Returns `(old_text, new_text)` for `FINDINGS.md` -- the one read this
    module needs regardless of `--write` or `--check`, factored out so
    both share it instead of drifting apart."""
    findings_path = root / FINDINGS_REL_PATH
    old_text = read_text(findings_path)
    new_block = build_index_block(collect_all_entries(root))
    new_text = replace_index_block(old_text, new_block)
    return old_text, new_text


def write_index(root: Path) -> bool:
    """Regenerates the index block in `FINDINGS.md` in place. Idempotent:
    calling this twice in a row makes no further change. Returns whether
    the file's content actually changed."""
    old_text, new_text = regenerated_findings_text(root)
    if new_text == old_text:
        return False
    (root / FINDINGS_REL_PATH).write_text(new_text, encoding="utf-8")
    return True


def check_index(root: Path) -> bool:
    """Returns whether the committed index block already matches what
    `write_index` would produce -- true means current, false means stale."""
    old_text, new_text = regenerated_findings_text(root)
    return new_text == old_text


# ==========================================================================
# CLI
# ==========================================================================


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", type=Path, default=None, help="repo root (default: derived from this file's location)")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate the index block in place")
    mode.add_argument("--check", action="store_true", help="exit 1 if the index block is stale, 0 if current")
    args = parser.parse_args(argv)

    root = (args.root or Path(__file__).resolve().parent.parent).resolve()

    if args.write:
        changed = write_index(root)
        print(f"{FINDINGS_REL_PATH}: index {'updated' if changed else 'already current'}")
        return 0

    if check_index(root):
        print(f"{FINDINGS_REL_PATH}: index is current")
        return 0
    print(
        f"{FINDINGS_REL_PATH}: index is stale -- run `python tools/index_findings.py --write` and commit the result",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
